name: "Terraform Plan"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  TF_CLOUD_HOSTNAME: "tfe-md-new-2.fawaz-akhtar.sbx.hashidemos.io"
  TF_CLOUD_ORGANIZATION: "fawaz"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "githubactions"

jobs:
  terraform:
    if: github.repository != 'hashicorp-education/learn-terraform-github-actions'
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Terraform Version
        run: terraform -v

      - name: Initialize Terraform
        run: terraform init
      
      - name: Validate Terraform
        run: terraform validate

      - name: Plan changes
        run: terraform plan
      
      - name: Apply changes
        run: terraform apply -auto-approve
      
      - name: Run additional tests
        run: |
          terraform state list
        continue-on-error: true

      - name: Destroy
        run: terraform destroy -auto-approve
